import { MigrationInterface, QueryRunner } from "typeorm";

export class SeedFiveUsers2026062617134543dffgdgd0 implements MigrationInterface {
    public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`CREATE EXTENSION IF NOT EXISTS "pgcrypto";`);

    // Fix: Make sure "users" matches the exact name generated by Entities.User
    await queryRunner.query(`
        INSERT INTO "User" (id, email, first_name, last_name, created_at, updated_at) VALUES 
        (gen_random_uuid(), 'john.doe@example.com', 'John', 'Doe', NOW(), NOW()),
        (gen_random_uuid(), 'jane.smith@example.com', 'Jane', 'Smith', NOW(), NOW()),
        (gen_random_uuid(), 'alex.jones@example.com', 'Alex', 'Jones', NOW(), NOW()),
        (gen_random_uuid(),'wel.done@example.com','Well','Done',NOW(),NOW()),
        (gen_random_uuid(),'vikas@example.com','vikas','dangi',Now(),Now())
        
        ON CONFLICT (email) DO NOTHING;
    `);
}


    public async down(queryRunner: QueryRunner): Promise<void> {
        // Delete the 5 seeded users if the migration is reverted
        // await queryRunner.query(`
        // INSERT INTO "User" (id, email, first_name, last_name, created_at, updated_at) VALUES 
        //     (gen_random_uuid(), 'dangi.radhe@example.com', 'Radhe', 'Dangi', NOW(), NOW())
        // `);
    }
}
